version: '3'

services:
    app:
        build: .
        command: gunicorn -w 4 -b :8888 app:app
        container_name: api.example.com        
        volumes: 
            - .:/appcode 
    web:
        build: ./nginx-proxy
        ports: 
            - "80:80"
        depends_on:
            - app
